INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Mezei Gábor', '2013-11-17', 1897, 'Kálmán Imre u.', 65, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Nemes Gergő', '2013-3-11', 1555, 'Hegyalja út', 15, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Bognár Benedek', '2013-4-24', 1337, 'Erzsébet krt.', 72, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Bálint Donát', '2013-10-23', 1981, 'Hegyalja út', 18, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Hegedüs Renátó', '2013-7-18', 1594, 'Eötvös út', 24, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szalai Róbert', '2013-8-19', 1118, 'Nánási út', 12, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Kende Ádám', '2013-2-14', 1154, 'Árpád fejedelem útja', 16, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Bogdán Sándor', '2013-9-14', 1972, 'Csabai kapu', 71, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Papp Bertalan', '2013-4-8', 1533, 'Baross tér', 64, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Molnár Mihály', '2013-9-2', 1766, 'Árpád fejedelem útja', 91, 1);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szalai Zsanett', '2012-5-27', 1948, 'Csabai kapu', 36, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szilágyi Erzsébet', '2012-1-16', 1823, 'Hegyalja út', 93, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Bakos Csenge', '2012-8-20', 1670, 'Agip u.', 35, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('László Tamara', '2012-5-8', 1290, 'Bécsi utca', 61, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Sándor Izabella', '2012-10-2', 1104, 'Bem rkp.', 75, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szűts Lili', '2012-3-28', 1748, 'Erzsébet tér', 60, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Pál Sára', '2012-5-18', 1598, 'Kis Diófa u.', 75, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Orosz Kinga', '2012-1-25', 1653, 'Szent Gellért tér', 61, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Jakab Anita', '2012-4-6', 1771, 'Kossuth Lajos u.', 12, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Király Zita', '2012-11-24', 1311, 'Dayka Gábor u.', 10, 2);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Tamás Zoltán', '2011-4-7', 1564, 'Erzsébet krt.', 83, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Faragó Boldizsár', '2011-10-3', 1778, 'Kárpát u.', 58, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Váradi Pál', '2011-4-2', 1146, 'Dayka Gábor u.', 13, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Kerekes Patrik', '2011-1-18', 1542, 'Victor Hugo u.', 79, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Fekete Ábel', '2011-8-6', 1212, 'Teréz krt.', 61, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Deák Krisztofer', '2011-4-8', 1745, 'Király u.', 38, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Bakos László', '2011-10-21', 1277, 'Eötvös út', 88, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Balog Donát', '2011-12-7', 1193, 'Wesselényi u.', 45, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Takács Henrik', '2011-9-22', 1284, 'Tompa u.', 43, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Kelemen Dezső', '2011-8-19', 1327, 'Kárpát u.', 27, 3);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Zobor Mercédesz', '2010-9-18', 1660, 'Munkácsy Mihály út', 40, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Márton Ramóna', '2010-5-7', 1535, 'Síp utca', 29, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szabó Dorina Mária', '2010-3-28', 1312, 'Hegyalja út', 63, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Pásztor Gabriella', '2010-3-13', 1107, 'Hegedûs Gyula utca', 18, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Székely Vanda', '2010-6-23', 1481, 'Hegedûs Gyula utca', 54, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Lengyel Mária', '2010-8-1', 1965, 'Nagytétényi út', 15, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Pintér Kíra', '2010-5-25', 1817, 'Bem rakpart', 64, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Jónás Szimonetta', '2010-11-7', 1807, 'Belgrád rkp.', 97, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Farkas Viktória', '2010-9-24', 1710, 'Veres Pálné u.', 26, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Péter Borbála', '2010-2-25', 1516, 'Kis Diófa u.', 87, 4);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Török Endre', '2009-9-13', 1535, 'Agip u.', 84, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Gál Olivér', '2009-12-28', 1618, 'Wesselényi u.', 26, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Székely Barnabás', '2009-6-15', 1549, 'Nánási út', 59, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szekeres János', '2009-7-18', 1172, 'Wesselényi u.', 99, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Juhász Márkó', '2009-6-6', 1925, 'Kossuth Lajos u.', 23, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Péter Ákos', '2009-11-19', 1729, 'Dózsa György út', 42, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Fehér Soma', '2009-1-7', 1846, 'Baross tér', 70, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Takács Norbert', '2009-9-27', 1950, 'Teréz krt.', 18, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Faragó Szilárd', '2009-2-18', 1614, 'Csavargyár u.', 45, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Somogyi Renátó', '2009-11-6', 1420, 'Apor Péter u.', 7, 5);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Bodnár Zsófia', '2008-3-11', 1859, 'Budaörsi út', 50, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Somogyi Nóra', '2008-3-24', 1656, 'Hegyalja út', 28, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Fábián Dorina', '2008-9-15', 1904, 'Szilágyi Erzsébet fasor', 64, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Varga Alexandra', '2008-8-27', 1391, 'Tas vezér u.', 10, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Biró Georgina', '2008-1-25', 1746, 'Apor Péter u.', 80, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Székely Petra', '2008-8-26', 1762, 'Síp utca', 46, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Fodor Hajnalka', '2008-12-12', 1711, 'Tompa u.', 64, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Gál Nikolett', '2008-5-17', 1764, 'Hegyalja út', 42, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Pintér Mária', '2008-8-22', 1608, 'Eötvös út', 99, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szűts Evelin', '2008-7-3', 1860, 'Síp utca', 34, 6);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Nagy Lajos', '2007-1-3', 1203, 'Bem rkp.', 36, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szűts István', '2007-8-21', 1899, 'Bem rakpart', 48, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Jónás Sándor', '2007-7-4', 1969, 'Erzsébet tér', 26, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Farkas Mihály', '2007-4-26', 1406, 'Eötvös út', 12, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('László Szabolcs', '2007-3-21', 1971, 'Kis Diófa u.', 43, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Bálint Erik', '2007-3-5', 1987, 'Szilágyi Erzsébet fasor', 59, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Németh Dezső', '2007-1-6', 1526, 'Bécsi utca', 42, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Gulyás Norbert', '2007-9-5', 1813, 'Nyár utca', 66, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Antal Zsolt', '2007-6-5', 1940, 'Kis Diófa u.', 33, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Balázs Ádám', '2007-4-5', 1608, 'Csabai kapu', 77, 7);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Balogh Csilla', '2006-10-22', 1261, 'Bem rkp.', 34, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Péter Andrea', '2006-11-15', 1637, 'Csabai kapu', 79, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Csonka Vanessza', '2006-6-26', 1934, 'Nyár utca', 67, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Halász Flóra', '2006-6-15', 1188, 'Piroska u.', 58, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Deák Melinda', '2006-12-19', 1515, 'Kárpát u.', 97, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Jónás Nikoletta', '2006-7-16', 1746, 'Agip u.', 66, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Bakos Liliána', '2006-3-24', 1443, 'Munkácsy Mihály út', 17, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Virág Lilla', '2006-11-23', 1602, 'Kossuth Lajos u.', 21, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Takács Martina', '2006-2-25', 1933, 'Bécsi utca', 75, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Gulyás Mercédesz', '2006-4-11', 1445, 'Dayka Gábor u.', 15, 8);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Török Zalán', '2005-3-26', 1867, 'Tas vezér u.', 56, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Kerekes Miklós', '2005-9-17', 1603, 'Tas vezér u.', 91, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Dobos Viktor', '2005-5-4', 1433, 'Teréz krt.', 55, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Orsós Bálint', '2005-8-2', 1955, 'Veres Pálné u.', 13, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Zobor Zoltán', '2005-8-25', 1589, 'Király u.', 18, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Oláh Zsolt', '2005-11-5', 1135, 'Nyár utca', 78, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Katona Rajmund', '2005-5-27', 1271, 'Kossuth Lajos u.', 87, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Kapolcs Lajos', '2005-11-2', 1393, 'Munkácsy Mihály út', 60, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Major Gergő', '2005-12-10', 1331, 'Rákóczi út', 68, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Soós Adrián', '2005-1-11', 1379, 'Szent Gellért tér', 55, 9);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Major Erzsébet', '2004-1-20', 1160, 'Bem rkp.', 92, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Dudás Natália', '2004-1-5', 1736, 'Belgrád rkp.', 33, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Simon Hajnalka', '2004-9-27', 1371, 'Szent Gellért tér', 41, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Pataki Brigitta', '2004-5-15', 1671, 'Erzsébet krt.', 71, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Faragó Georgina', '2004-11-2', 1564, 'Victor Hugo u.', 82, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Csatár Patrícia', '2004-2-19', 1411, 'Piroska u.', 84, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Lengyel Réka', '2004-2-15', 1357, 'Árpád fejedelem útja', 43, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Rácz Anikó', '2004-10-11', 1890, 'Izabella u.', 65, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Székely Luca', '2004-8-18', 1725, 'Király u.', 3, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Kerekes Lili', '2004-10-28', 1486, 'Csavargyár u.', 83, 10);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Nagy Miklós', '2003-8-5', 1558, 'Wesselényi u.', 11, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Dudás Béla', '2003-3-11', 1317, 'Nyár utca', 66, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Hajdú Richárd', '2003-3-1', 1639, 'Erzsébet tér', 11, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Tóth Benjámin', '2003-2-18', 1167, 'Árpád fejedelem útja', 59, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Papp Adrián', '2003-5-11', 1384, 'Nyár utca', 99, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Balázs Viktor', '2003-9-6', 1119, 'Apor Péter u.', 62, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Halász Péter', '2003-6-5', 1246, 'Árpád fejedelem útja', 32, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Kapolcs Renátó', '2003-12-20', 1372, 'Csabai kapu', 74, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Oláh Áron', '2003-6-10', 1623, 'Hegyalja út', 81, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Fodor Roland', '2003-11-18', 1134, 'Nagytétényi út', 4, 11);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Szőke Elizabet', '2002-11-10', 1446, 'Kossuth Lajos u.', 98, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Fazekas Mónika', '2002-9-4', 1172, 'Bem rkp.', 80, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Csonka Nikolett', '2002-11-26', 1476, 'Rákóczi út', 81, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Novák Dalma', '2002-5-13', 1417, 'Dózsa György út', 55, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Balog Rebeka', '2002-2-12', 1928, 'Victor Hugo u.', 35, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Csatár Natália', '2002-7-12', 1505, 'Hegedûs Gyula utca', 27, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Sándor Andrea', '2002-6-26', 1487, 'Szent Gellért tér', 31, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Deák Szilvia', '2002-12-20', 1812, 'Kárpát u.', 2, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Vörös Virág', '2002-10-20', 1592, 'Nagytétényi út', 88, 12);
INSERT INTO Diakok (nev, szul_datum, iranyitoszam, utca, hazszam, hanyadikos) VALUES ('Somogyi Anit', '2002-9-4', 1881, 'Dayka Gábor u.', 54, 12);
